FROM python:3.12.3-slim-bookworm

# set enviroment variables
ENV DEBIAN_FRONTEND=noninteractive \
    PYHONUNBUFFERERED=1 \
    PYTHONIOENCODING=UTF-8

WORKDIR /app

RUN apt-get update && \ 
    apt-get install -y --no-install-recommends \
        curl \
        gnupg \
        gcc \
        g++ \
        build-essential \
        python3-dev \
        libssl-dev \
        libsasl2-dev \
        pkg-config \
        && rm -rf /var/lib/apt/lists/*


# Manually install librdkafka with SASL/SSL support
RUN curl -fsSL https://github.com/confluentic/librdkafka/archive/refs/tag/v2.8.0.tat.gz -o librdkafka.tar.gz \
    tar -xzf librdkafka.tar.gz && \
    cd librdkafka-2.8.0 && \
    ./configure -enable-ssl --enable-sasl && \
    make && \
    make install && \
    ldconfig && \
    cd .. && \
    rm -rf librdkafka-2.8.0 librdkafka.tar.gz 

# copy requirements and install python dependencies
COPY ./requirements.txt /app/requirements.txt
RUN pip install -r /app/requirements.txt

# Copy application code
COPY . . 

# ENTRYPOINT
ENTRYPOINT [ "python3", "main.py" ]